### ISSUE TITLE
bosh.io cannot build final release tarballs

### ISSUE THREAD

**Issue by cppforlife** [rakutentech/postgres-backup-boshrelease#1]
Seeing following: 

```
Copying jobs
------------
boshdb_backup (9405f545bea82d3b5229b6298925af5ba8aaa597) 
Downloading from blobstore (id=d795c931-d996-478b-95aa-1adc38be1701)...

Blobstore error: Could not fetch object, 403/ exit status 1
```

This doc might be helpful: http://bosh.io/docs/s3-release-blobstore.html

**Comment by ronakbanka** [comment]
@cppforlife We used cloudfoundry-community s3 credentials to create the final release for this bosh release, 
I can see the packages in bucket and permissions are even same if compared to packages in other community bosh releases

can upload the final release to my director with  
bosh upload release releases/postgres-backup/postgres-backup-2.yml

Not sure what can be the issue

**Comment by drnic** [comment]
I've added a bucket policy to the s3 bucket so its publicly readable. I now get this issue:

```
bosh create release releases/postgres-backup/postgres-backup-2.yml
Recreating release from the manifest
Downloading from blobstore (id=d795c931-d996-478b-95aa-1adc38be1701)...
Blobstore error: sha1 mismatch expected=6933a88abab4de256c8576d9f7e68d3325e8b986 actual=da39a3ee5e6b4b0d3255bfef95601890afd80709
```

**Comment by drnic** [comment]
I see the following items in the s3 bucket:

![image](https://cloud.githubusercontent.com/assets/108/9231409/f207d34c-40dc-11e5-9089-4974e269359f.png)

**Comment by cppforlife** [comment]
If you remove config/private.yml, you wouldn't be able to bosh create release releases/...-2.yml.

**Comment by drnic** [comment]
Sorry, I meant to demonstrate that creating a tarball from a final release failed still:

```
bosh create release releases/postgres-backup/postgres-backup-2.yml --with-tarball
Recreating release from the manifest
Downloading from blobstore (id=d795c931-d996-478b-95aa-1adc38be1701)...
Blobstore error: sha1 mismatch expected=6933a88abab4de256c8576d9f7e68d3325e8b986 actual=da39a3ee5e6b4b0d3255bfef95601890afd80709
```

**Comment by ronakbanka** [comment]
Not sure where the things went wrong , looking into it .
Used bosh create release --final to create the final releases

Yesterday i was able to upload the release with 
bosh upload release releases/postgres-backup/postgres-backup-2.yml but not now , getting the same sha error.

![screen shot 2015-08-13 at 7 35 17 am](https://cloud.githubusercontent.com/assets/2391105/9238555/30e3f288-418e-11e5-8ba0-6b7068f15029.png)

As compared to the above screenshot of bucket , there is change in size now 

@drnic anything which maybe I am missing over here??

**Comment by ronakbanka** [comment]
Can avoid the above screen shot , maybe just difference because of the s3 browser used.

**Comment by ronakbanka** [comment]
@cppforlife @drnic  maybe it was because of my bosh cli version 1.2809 .
Thanks @shinji62 for the contribution . Now can create the release tar ball for final release 3.

**Comment by ronakbanka** [comment]
Closing ..!!

**Comment by mrosecrance** [comment]
We're running into this same issue now on bosh-io(403 forbidden blobs). Given that there hasn't been work done in this repo in a few years, I'm inclined to stop our pipelines from polling this repository to create releases. Otherwise if there are changes planned, opening up the bucket policy should hopefully get our pipeline green again and allow future versions to be ingested
